---
name: Lint & Test
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - run: go test .

  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false

    - uses: golangci/golangci-lint-action@v3
